name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  dio: ^5.9.1
  provider: ^6.1.5
  shared_preferences: ^2.5.4
  razorpay_flutter: ^1.4.0
  go_router: ^17.1.0
  video_player: ^2.8.1
  google_maps_flutter: ^2.6.1
  geolocator: ^10.1.0
  url_launcher: ^6.2.2
  flutter_polyline_points: ^2.0.1
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/videos/splash_video.mp4
